<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pacifico</name>
   <tag></tag>
   <elementGuidId>b9b415c8-7366-49c6-8f03-0068234487ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-1-content&quot;]/div[1]/div/div/form/div/div[2]/div/div[2]/p-dropdown/div/div[3]/div/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
