<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RutasGeneradas</name>
   <tag></tag>
   <elementGuidId>5f41143c-7c77-4ff4-9fce-e86d15f369e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-main/div/div/div[2]/planeamientoform/div/div[9]/p-toolbar/div/div[1]/md-chip-list/div/md-chip[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
