<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Italika</name>
   <tag></tag>
   <elementGuidId>15c7dc0c-1603-4ef8-b322-8fb8e6d30695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-3-content&quot;]/div[1]/div/div/form/div/div[1]/div/div[2]/p-dropdown/div/div[3]/div[2]/ul/li[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
