<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CoberturaAmplia</name>
   <tag></tag>
   <elementGuidId>d48f1895-47a7-4110-9276-cd3ad29bd68b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-1-content&quot;]/div[1]/div/div/form/div/div[2]/div/div[1]/p-dropdown/div/div[3]/div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
