<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Asociado_Ingresar</name>
   <tag></tag>
   <elementGuidId>09f6ebbd-2077-4cc3-8ecb-7b002dfb5633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-1-content&quot;]/div[1]/div/div/div/div/div/div/p-autocomplete/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
