<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Motocicleta</name>
   <tag></tag>
   <elementGuidId>93f49b66-970a-4620-922d-7a83d6b7b1c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-3-content&quot;]/div[1]/div/div/form/div/div[1]/div/div[1]/p-dropdown/div/div[3]/div/ul/li[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
