<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rutas generadas (363)</name>
   <tag></tag>
   <elementGuidId>9083b2b1-8000-4786-a04a-2f5ba135774f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//md-chip[(text() = 'Rutas generadas (363)' or . = 'Rutas generadas (363)')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-main/div/div/div[2]/planeamientoform/div/div[9]/p-toolbar/div/div[1]/md-chip-list/div/md-chip[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-chip</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-chip mat-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rutas generadas (363)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main[@class=&quot;ng-tns-c5-2 ng-star-inserted&quot;]/div[@class=&quot;layout-wrapper layout-compact&quot;]/div[@class=&quot;layout-container menu-layout-overlay&quot;]/div[@class=&quot;layout-main&quot;]/planeamientoform[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ui-g ui-fluid dashboard&quot;]/div[@class=&quot;ui-g-12&quot;]/p-toolbar[1]/div[@class=&quot;ui-toolbar ui-widget ui-widget-header ui-corner-all ui-helper-clearfix&quot;]/div[@class=&quot;ui-toolbar-group-left&quot;]/md-chip-list[@class=&quot;mat-chip-list&quot;]/div[@class=&quot;mat-chip-list-wrapper&quot;]/md-chip[@class=&quot;mat-chip mat-primary&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders (0)'])[1]/following::md-chip[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repros'])[1]/following::md-chip[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrito recojo'])[1]/preceding::md-chip[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//md-chip[2]</value>
   </webElementXpaths>
</WebElementEntity>
