<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FechaVencimientoSeguro</name>
   <tag></tag>
   <elementGuidId>b3ea42ef-05b4-4926-93ba-e03315941299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-1-content&quot;]/div[1]/div/div/form/div/div[1]/div/div[2]/p-calendar/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
