<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ComboBox-EstadoAsociado-Blockeado</name>
   <tag></tag>
   <elementGuidId>afe3387e-4063-45dc-83a1-aa2851e89454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-1-content&quot;]/div[1]/div/div[3]/div/div[3]/p-dropdown/div/div[3]/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
