<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Licencia-Categoria-A3</name>
   <tag></tag>
   <elementGuidId>da213d8f-2259-49e8-b431-274ea3d72b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-3-content&quot;]/div[1]/div/div[6]/div/div[1]/p-dropdown/div/div[3]/div/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
