<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Licencia-Categoria-A2</name>
   <tag></tag>
   <elementGuidId>0f8e8554-9f5d-4fef-b05a-90f7a725205f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-3-content&quot;]/div[1]/div/div[6]/div/div[1]/p-dropdown/div/div[3]/div/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
